version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "iheart-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g6olbs1gu9v0"
s3_prefix = "iheart-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
